name: Code Quality Check (Flake8)

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  code-quality:
    name: Code Quality Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies and flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          if [ -f app/requirements.txt ]; then pip install -r app/requirements.txt; fi

      - name: Run flake8 code quality check
        run: |
          echo "Running flake8 code quality checks..."
          flake8 --config .flake8 app/ model/ tests/
          echo "✅ Code quality check passed!"

      - name: Comment on PR (if applicable)
        if: github.event_name == 'pull_request' && success()
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ Code quality check passed! Your code follows the project standards.'
            })
